# Generated by Django 4.2.7 on 2023-12-08 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
